#!/bin/bash
#SBATCH --job-name=import
#SBATCH --output=log_import.out
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=00:30:00
#SBATCH --hint=nomultithread
#SBATCH --qos=qos_gpu_h100-dev
#SBATCH --account=wuh@h100
#SBATCH --constraint=h100

source ../set_env.sh

export HF_DATASETS_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export HF_HUB_OFFLINE=1

echo $1 

python -m torch.distributed.launch --nproc_per_node 1 hf_to_nemo.py --hf_model Lucie-7B-Instruct-v1.1
